name: precommit
permissions: read-all
concurrency:
  group: precommit-${{ github.event.pull_request.number }}
  cancel-in-progress: true
jobs:
  pytest:
    uses: ./.github/workflows/call_precommit.yml
    with:
      python_version: 3.10.14
      gpu_enabled: true
    secrets: inherit
env:
  GERALT_SECRET: ${{ secrets.GERALT }}
on:
  pull_request:
    paths-ignore:
    - '**/*.md'
    - .ci/*
    - docs/**/*
    - examples/**/*
    - licensing/*
    - tests/post_training/*
    - tests/cross_fw/examples/*
